name: AutoUpdate

on:
  # 毎年4月1日0時に実行(韓国時間)
  schedule:
    - cron: '0 15 31 3 *'
  ## 手動実行用
  workflow_dispatch:

# ジョブ設定
jobs:
  AutoUpdateJob:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - name: Checkout
        uses: actions/checkout@v3
      # Pythonインストール
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      # pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      # ConvertHanjaDict.py実行
      - name: Run ConvertHanjaDict.py
        run: python convert_dict/ConvertHanjaDict.py
      # ゴミファイル削除
      - name: Remove trash files
        run: rm -rf hanja.txt freq-hanja.txt freq-hanjaeo.txt convert_dict/__pycache__/
      # プッシュ
      - name: Push
        run: |
          git config user.name  "actions-user"
          git config user.email "action@github.com"
          git add koromaja.hanja.dict.yaml
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto Update"
            git push origin master
          fi
